# Generated by Django 5.2.17 on 2026-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailverificationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_welcome',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
