# Generated by Django 5.2.17 on 2026-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_has_seen_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
