# Generated by Django 5.2.17 on 2026-10-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_usage', to='referrals.referralcode'),
        ),
    ]
