# Generated by Django 5.2.17 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referral_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='bonus_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='source',
            field=models.CharField(choices=[('MEMBERSHIP', 'Membership'), ('CONCIERGE', 'Concierge')], default='MEMBERSHIP', max_length=20),
        ),
    ]
