# Generated by Django 5.2.17 on 2026-10-07 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referral_bonus_granted_at_commission_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='covered_commissions',
            field=models.ManyToManyField(blank=True, related_name='payouts', to='referrals.commission'),
        ),
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('amount', models.BigIntegerField(default=0)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
