# Generated by Django 5.2.17 on 2026-10-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_payout_covered_commissions_payout_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralFraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='withdrawal_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralfraudflag',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_fraud_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralfraudflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_referral_fraud_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='referralfraudflag',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('referrer', 'code'), name='unique_active_referral_fraud_flag'),
        ),
    ]
