# Generated by Django 5.2.17 on 2026-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
