# Generated by Django 5.2.17 on 2026-09-14 19:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_storefrontsettings'),
        ('inventory', '0002_inventoryitem_description_inventoryitem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_address', models.TextField(blank=True)),
                ('delivery_option', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('both', 'Both')], max_length=20)),
                ('status', models.CharField(choices=[('pending_whatsapp', 'Pending WhatsApp'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending_whatsapp', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paystack_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_orders', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='StorefrontOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='businesses.storefrontorder')),
            ],
        ),
    ]
