# Generated by Django 5.2.17 on 2026-09-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_storefrontorder_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontsettings',
            name='business_type_hint',
            field=models.CharField(blank='', choices=[('products', 'Products'), ('services', 'Services'), ('both', 'Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='storefrontsettings',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='businesses.business')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_visible_on_storefront', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
