services:
  - type: web
    name: vendari-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn vendari_api.wsgi:application --workers 2 --threads 4 --timeout 60 --keep-alive 5 --max-requests 1000 --max-requests-jitter 100
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: CLOUDINARY_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: VENDARI_LOGO_URL
        sync: false
      - key: WHATSAPP_CATALOG_ID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GOOGLE_FRONTEND_REDIRECT_URI
        sync: false