# Generated by Django 5.2.17 on 2026-08-22 23:13

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_amount_plan_interval_feature_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='feature_flags',
            field=models.JSONField(default=billing.models.default_feature_flags),
        ),
    ]
