# Generated by Django 5.2.17 on 2026-10-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_membership_payments_and_webhook_events'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webhookevent',
            name='unique_webhook_event_reference',
        ),
    ]
