# Generated by Django 5.2.17 on 2026-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_remove_webhookevent_unique_webhook_event_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
