'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowRight, BarChart3, BookOpen, CheckCircle2, CircleHelp, ClipboardList, HelpCircle, Package, Search, ShoppingCart, Store, Users } from 'lucide-react'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'

const topics = [
  { id: 'start', label: 'Start here', icon: BookOpen, href: '/dashboard' },
  { id: 'sales', label: 'Sales', icon: ShoppingCart, href: '/dashboard/sales' },
  { id: 'inventory', label: 'Inventory', icon: Package, href: '/dashboard/inventory' },
  { id: 'storefront', label: 'Storefront', icon: Store, href: '/dashboard/storefront' },
  { id: 'reports', label: 'Reports', icon: BarChart3, href: '/dashboard/reports' },
  { id: 'team', label: 'Team access', icon: Users, href: '/dashboard/team' },
]

const guides = [
  { id: 'first-week', topic: 'start', title: 'Your first week in Vendari', summary: 'Set up the essentials and build a daily rhythm that keeps your numbers trustworthy.', steps: ['Confirm your business details in Settings.', 'Add products with a selling price, stock count, reorder level, description, and useful photos.', 'Record every sale as it happens so stock and revenue stay aligned.', 'Log expenses as they occur instead of reconstructing them later.', 'Review the dashboard and Reports at the end of the week.'], href: '/dashboard' },
  { id: 'inventory', topic: 'inventory', title: 'Keep inventory accurate', summary: 'Know what is on the shelf before a customer asks for it.', steps: ['Add each product once and use a clear product name or code.', 'Set quantity in stock and a reorder level that reflects supplier lead time.', 'Use up to six product photos and a customer-friendly description for storefront items.', 'Record sales and restocks promptly.', 'Investigate low-stock alerts before they become stockouts.'], href: '/dashboard/inventory' },
  { id: 'sales', topic: 'sales', title: 'Record a sale correctly', summary: 'Capture the transaction once, with enough detail to understand the day later.', steps: ['Choose the product and enter the quantity sold.', 'Confirm the selling price and payment method.', 'Save the sale immediately after payment.', 'Check the dashboard trend and inventory quantity when needed.'], href: '/dashboard/sales' },
  { id: 'storefront', topic: 'storefront', title: 'Launch your online storefront', summary: 'Create a shareable shop that reflects your business and is ready to receive orders.', steps: ['Open Storefront and choose your slug, theme, colors, contact details, and delivery option.', 'Open Manage storefront products and make sure each item is priced and visible.', 'Add product descriptions and photos so customers can decide confidently.', 'Preview the public link on mobile before sharing it.', 'Test the cart and checkout path once.'], href: '/dashboard/storefront' },
  { id: 'reports', topic: 'reports', title: 'Read your business numbers', summary: 'Use Reports to understand where money is coming from and where it is going.', steps: ['Choose a date range that matches the question you are asking.', 'Compare revenue with expenses before making a decision.', 'Look at product and payment trends, not only the headline total.', 'Use the result to choose one action for the next week.'], href: '/dashboard/reports' },
  { id: 'team', topic: 'team', title: 'Invite the right people', summary: 'Give staff and accountants access without sharing your password.', steps: ['Open Team and enter the person’s email address.', 'Choose Staff for daily operations or Accountant for money and reports.', 'Vendari emails a one-time invitation with an acceptance link and code.', 'The invitee accepts with the invited email and creates a password if needed.', 'Review roles regularly and remove access when someone leaves.'], href: '/dashboard/team' },
]

const faqs = [
  ['How does profit work?', 'Profit is calculated from recorded sales revenue minus recorded expenses. Accurate results depend on recording both sides consistently.'],
  ['How do low-stock alerts work?', 'An item is considered low stock when its quantity is at or below the reorder level you set. Increase the quantity after receiving stock and adjust the reorder level when your supply pattern changes.'],
  ['Can I change my storefront after publishing?', 'Yes. Storefront settings, products, visibility, theme, colors, delivery options, and social links can be updated from the Storefront area.'],
  ['What happens when I invite a teammate?', 'Vendari sends the address you entered an email containing the business name, role, a one-time code, and an acceptance link. The invite expires after seven days.'],
  ['What can an invited teammate access?', 'After acceptance, the teammate signs into the same dashboard and receives the Staff or Accountant role selected by the owner. Owners can change that role or remove access from Team.'],
  ['Why are my dashboard numbers not what I expected?', 'Check the selected date range, confirm every sale and expense was recorded once, and review product prices and quantities in Inventory.'],
]

export default function HelpPage() {
  const [query, setQuery] = useState('')
  const [topic, setTopic] = useState('all')
  const filteredGuides = useMemo(() => guides.filter((guide) => {
    const matchesTopic = topic === 'all' || guide.topic === topic
    const haystack = `${guide.title} ${guide.summary} ${guide.steps.join(' ')}`.toLowerCase()
    return matchesTopic && (!query.trim() || haystack.includes(query.trim().toLowerCase()))
  }), [query, topic])

  return <div className="dashboard-page"><main className="mx-auto max-w-7xl space-y-8">
    <section className="relative overflow-hidden rounded-2xl border border-blue/20 bg-surface px-6 py-8 shadow-sm sm:px-10 sm:py-10">
      <div className="relative z-10 max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-blue">Vendari help center</p><h1 className="mt-3 font-display text-3xl font-semibold text-ink sm:text-5xl">Know what to do next.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-text-secondary">Practical answers for running your business: record the work, keep your stock honest, understand your numbers, and make your storefront easier to trust.</p><div className="relative mt-7 max-w-2xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search guides, inventory, storefront, reports..." className="dashboard-input h-14 w-full rounded-lg pl-12 pr-4 text-sm" aria-label="Search help" /></div></div><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-brand-gradient opacity-10" /></section>

    <section><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-text-muted">Browse by task</p><h2 className="mt-2 font-display text-2xl font-semibold text-ink">Find the answer in context</h2></div><CircleHelp className="h-7 w-7 text-blue" /></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{topics.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setTopic(topic === id ? 'all' : id)} className={`flex min-h-24 flex-col items-start justify-between rounded-xl border p-4 text-left transition-all hover:-translate-y-0.5 hover:shadow-md ${topic === id ? 'border-blue bg-blue/5 text-blue' : 'border-border bg-surface text-text-secondary'}`}><Icon className="h-5 w-5" /><span className="text-sm font-semibold">{label}</span></button>)}</div></section>

    <section><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-text-muted">Guides</p><h2 className="mt-2 font-display text-2xl font-semibold text-ink">Useful workflows</h2></div><span className="text-sm text-text-muted">{filteredGuides.length} guide{filteredGuides.length === 1 ? '' : 's'}</span></div>{filteredGuides.length ? <div className="grid gap-4 lg:grid-cols-2">{filteredGuides.map((guide) => <article key={guide.id} className="rounded-xl border border-border bg-surface p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h3 className="font-display text-xl font-semibold text-ink">{guide.title}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{guide.summary}</p></div><ClipboardList className="h-5 w-5 shrink-0 text-blue" /></div><ol className="mt-5 space-y-3">{guide.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-text-secondary"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue/10 text-xs font-semibold text-blue">{index + 1}</span><span>{step}</span></li>)}</ol><Link href={guide.href} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue hover:underline">Open {guide.title.split(' ')[0]} <ArrowRight className="h-4 w-4" /></Link></article>)}</div> : <div className="rounded-xl border border-dashed border-border bg-surface px-6 py-12 text-center"><HelpCircle className="mx-auto h-8 w-8 text-text-muted" /><p className="mt-3 font-semibold text-ink">No guide matches that search.</p><button type="button" onClick={() => { setQuery(''); setTopic('all') }} className="mt-2 text-sm font-semibold text-blue hover:underline">Clear search</button></div>}</section>

    <section className="grid gap-6 lg:grid-cols-[1.25fr_0.75fr]"><div className="rounded-xl border border-border bg-surface p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><BookOpen className="h-5 w-5 text-blue" /><h2 className="font-display text-2xl font-semibold text-ink">Frequently asked</h2></div><Accordion type="single" collapsible className="mt-4">{faqs.map(([question, answer], index) => <AccordionItem key={question} value={`faq-${index}`}><AccordionTrigger className="text-left text-sm font-semibold text-ink hover:text-blue">{question}</AccordionTrigger><AccordionContent className="text-sm leading-6 text-text-secondary">{answer}</AccordionContent></AccordionItem>)}</Accordion></div><div className="rounded-xl bg-ink p-6 text-white shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue">A calm first week</p><h2 className="mt-3 font-display text-2xl font-semibold">Make the numbers useful.</h2><p className="mt-3 text-sm leading-6 text-white/70">Small, consistent updates beat a long catch-up session. Record the sale, log the expense, and check what is low before you close the day.</p><div className="mt-6 space-y-3 text-sm text-white/85"><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-blue" />Every sale recorded</p><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-blue" />Every expense captured</p><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-blue" />Low stock reviewed</p><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-blue" />Storefront tested before sharing</p></div><Link href="/dashboard" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-brand-gradient px-4 py-2.5 text-sm font-semibold text-white">See your dashboard <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main></div>
}
