# Generated by Django 5.2.17 on 2026-08-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_insights', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='businesses.business'),
        ),
    ]
