'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Clock3, Facebook, Globe, Images, Instagram, MapPin, Minus, Music2, Phone, Plus, ShoppingBag, ShoppingCart, X } from 'lucide-react'
import { getStorefrontCartKey } from '@/lib/storefront'
import { checkoutStorefront } from '@/app/actions/storefront'
import { getStorefrontTheme } from '@/lib/storefront-themes'

type Product = { id: number; product_name: string; description: string; image: string | null; images?: string[]; selling_price: string | number | null; in_stock: boolean }
type Service = { name: string; description: string; price: string | number | null; image: string | null }
type GalleryImage = { image: string; caption: string }
type StorefrontData = {
  business_name: string
  address: string
  phone: string
  storefront: { slug: string; logo: string | null; social_links: Record<string, string>; theme: string; primary_color: string; accent_color: string; banner_image: string | null; description: string; about: string; whatsapp_number: string; delivery_option: string; opening_hours: Record<string, string>; business_type_hint: 'products' | 'services' | 'both' | ''; product_display_mode: 'flexed' | 'block' }
  items: Product[]
  services: Service[]
  gallery_images: GalleryImage[]
  opening_hours: Record<string, string>
  has_payments_enabled: boolean
}
type CartLine = Product & { quantity: number }

const SOCIAL_PLATFORMS = [
  { key: 'instagram', label: 'Instagram', icon: Instagram },
  { key: 'facebook', label: 'Facebook', icon: Facebook },
  { key: 'tiktok', label: 'TikTok', icon: Music2 },
  { key: 'twitter', label: 'Twitter/X', icon: Globe },
] as const

function excerpt(value: string) { return value.length > 92 ? `${value.slice(0, 92).trim()}...` : value }
function money(value: string | number | null) { return value === null ? 'Message us for price' : `N${Number(value).toLocaleString('en-NG', { minimumFractionDigits: 2 })}` }
function whatsappUrl(number: string, message: string) { const digits = number.replace(/\D/g, ''); return digits ? `https://wa.me/${digits}?text=${encodeURIComponent(message)}` : '' }

export default function StorefrontClient({ data }: { data: StorefrontData }) {
  const { storefront } = data
  const [cart, setCart] = useState<CartLine[]>(() => { if (typeof window === 'undefined') return []; try { return JSON.parse(window.localStorage.getItem(getStorefrontCartKey(storefront.slug)) || '[]') as CartLine[] } catch { return [] } })
  const [cartOpen, setCartOpen] = useState(false)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [checkoutError, setCheckoutError] = useState('')
  const [inquiryService, setInquiryService] = useState<Service | null>(null)
  const [inquiryForm, setInquiryForm] = useState({ name: '', phone: '', message: '' })
  const theme = storefront.theme || 'classic'
  const themePreset = getStorefrontTheme(theme)
  const primary = storefront.primary_color || themePreset.primary
  const accent = storefront.accent_color || themePreset.accent
  const isBold = theme === 'bold'
  const isMinimal = theme === 'minimal'
  const themeClass = isBold ? 'tracking-wide' : isMinimal ? 'font-light' : ''
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0)
  const total = cart.reduce((sum, item) => sum + Number(item.selling_price) * item.quantity, 0)
  const [form, setForm] = useState({ customer_name: '', customer_phone: '', customer_address: '', delivery_option: storefront.delivery_option || 'both', checkout_method: data.has_payments_enabled ? 'pay_now' as const : 'whatsapp' as const })
  const services = data.services || []
  const galleryImages = data.gallery_images || []
  const openingHours = data.opening_hours || storefront.opening_hours || {}
  const hasHours = Object.values(openingHours).some(Boolean)
  const hasContact = Boolean(data.address?.trim() || data.phone?.trim() || hasHours)
  const socialLinks = SOCIAL_PLATFORMS.filter(({ key }) => storefront.social_links?.[key])
  const blockProducts = storefront.product_display_mode === 'block'

  useEffect(() => { window.localStorage.setItem(getStorefrontCartKey(storefront.slug), JSON.stringify(cart)) }, [cart, storefront.slug])
  const addToCart = (product: Product) => { if (product.selling_price === null || Number(product.selling_price) <= 0) return; setCart((current) => { const existing = current.find((item) => item.product_name === product.product_name); return existing ? current.map((item) => item.product_name === product.product_name ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }] }) }
  const updateQuantity = (name: string, delta: number) => setCart((current) => current.flatMap((item) => item.product_name !== name ? [item] : item.quantity + delta > 0 ? [{ ...item, quantity: item.quantity + delta }] : []))
  const submitCheckout = async (event: React.FormEvent) => { event.preventDefault(); setSubmitting(true); setCheckoutError(''); const result = await checkoutStorefront(storefront.slug, { ...form, items: cart.map((item) => ({ product_name: item.product_name, quantity: item.quantity })) }); setSubmitting(false); if (!result.success) { setCheckoutError(result.error); return }; if (form.checkout_method === 'whatsapp' && result.data.whatsapp_url) { window.open(result.data.whatsapp_url, '_blank', 'noopener,noreferrer'); setCheckoutOpen(false); setCart([]); return }; if (result.data.authorization_url) window.location.assign(result.data.authorization_url) }
  const submitInquiry = (event: React.FormEvent) => { event.preventDefault(); const url = whatsappUrl(storefront.whatsapp_number, `Hello ${data.business_name}, I am interested in your service: ${inquiryService?.name}.\n\n${inquiryForm.message}\n\nName: ${inquiryForm.name}\nPhone: ${inquiryForm.phone}`); if (url) window.open(url, '_blank', 'noopener,noreferrer'); setInquiryService(null); setInquiryForm({ name: '', phone: '', message: '' }) }

  const renderProduct = (product: Product) => { const hasPrice = product.selling_price !== null && Number(product.selling_price) > 0; const canAdd = product.in_stock && hasPrice; return <article key={product.id} className={`group overflow-hidden border border-slate-200 bg-white shadow-sm ${themePreset.radius} ${blockProducts ? 'sm:flex sm:items-stretch' : ''}`}><Link href={`/s/${encodeURIComponent(storefront.slug)}/products/${product.id}`} className={`block ${blockProducts ? 'sm:flex sm:min-w-0 sm:flex-1' : ''}`}><div className={`${blockProducts ? 'sm:aspect-auto sm:w-64 lg:w-80' : 'aspect-[4/3] sm:aspect-square'} bg-slate-100`}>{product.image ? <img src={product.image} alt={product.product_name} className="h-full w-full object-cover transition-transform group-hover:scale-105" /> : <div className="flex h-full min-h-32 items-center justify-center" style={{ color: primary }}><ShoppingBag className="h-10 w-10 opacity-40" /></div>}</div><div className={`p-4 ${blockProducts ? 'sm:flex sm:flex-1 sm:flex-col sm:justify-center sm:p-6' : ''}`}><div className="mb-2 flex items-start justify-between gap-2"><h3 className="min-w-0 text-base font-semibold leading-tight">{product.product_name}</h3><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-semibold ${product.in_stock ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{product.in_stock ? 'In stock' : 'Out of stock'}</span></div>{product.description && <p className="mb-3 text-sm leading-5 text-slate-500">{excerpt(product.description)}</p>}<p className="text-lg font-bold" style={{ color: accent }}>{hasPrice ? money(product.selling_price) : 'Message us for price'}</p></div></Link><div className={`border-slate-200 p-3 ${blockProducts ? 'border-t sm:flex sm:w-44 sm:items-center sm:border-l sm:border-t-0' : 'border-t'}`}><button type="button" onClick={() => { if (canAdd) { addToCart(product); setCartOpen(true) } }} disabled={!canAdd} className="flex w-full items-center justify-center gap-2 rounded-xl px-3 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50" style={{ backgroundColor: canAdd ? accent : '#94a3b8' }}><ShoppingCart className="h-4 w-4" />{canAdd ? 'Add to cart' : 'Unavailable'}</button></div></article> }
  const sections = {
    about: storefront.about?.trim() && <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14" aria-labelledby="about-heading"><p className="text-sm font-semibold" style={{ color: accent }}>About</p><h2 id="about-heading" className="mt-1 text-2xl font-bold sm:text-3xl">A little more about us</h2><p className="mt-4 max-w-3xl whitespace-pre-line text-base leading-7 text-slate-600">{storefront.about}</p></section>,
    services: services.length > 0 && <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14" aria-labelledby="services-heading"><p className="text-sm font-semibold" style={{ color: accent }}>What we offer</p><h2 id="services-heading" className="mt-1 text-2xl font-bold sm:text-3xl">Services</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <article key={service.name} className={`overflow-hidden border border-slate-200 bg-white shadow-sm ${isMinimal ? 'rounded-none' : isBold ? 'rounded-3xl' : 'rounded-2xl'}`}>{service.image && <img src={service.image} alt="" className="aspect-[4/3] w-full object-cover" />}<div className="p-5"><h3 className="text-lg font-semibold">{service.name}</h3>{service.description && <p className="mt-2 text-sm leading-6 text-slate-500">{service.description}</p>}<p className="mt-4 font-bold" style={{ color: accent }}>{service.price === null ? 'Contact for pricing' : money(service.price)}</p><button type="button" onClick={() => setInquiryService(service)} className="mt-4 w-full rounded-xl px-3 py-2.5 text-sm font-semibold text-white" style={{ backgroundColor: accent }}>Inquire</button></div></article>)}</div></section>,
    gallery: galleryImages.length > 0 && <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14" aria-labelledby="gallery-heading"><div className="flex items-center gap-2"><Images className="h-5 w-5" style={{ color: accent }} /><h2 id="gallery-heading" className="text-2xl font-bold sm:text-3xl">Gallery</h2></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{galleryImages.map((item, index) => <figure key={`${item.image}-${index}`} className="overflow-hidden rounded-xl bg-slate-100"><img src={item.image} alt={item.caption || `${data.business_name} gallery image ${index + 1}`} className="aspect-square h-full w-full object-cover transition-transform hover:scale-105" />{item.caption && <figcaption className="bg-white px-3 py-2 text-sm text-slate-600">{item.caption}</figcaption>}</figure>)}</div></section>,
    products: data.items.length > 0 && <section className={`mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14 ${isMinimal ? 'bg-white' : isBold ? 'bg-slate-50' : ''}`} aria-labelledby="products-heading"><div className="mb-6 flex items-end justify-between gap-3"><div><p className="text-sm font-semibold" style={{ color: accent }}>Shop collection</p><h2 id="products-heading" className="mt-1 text-2xl font-bold sm:text-3xl">Available products</h2></div><button type="button" onClick={() => setCartOpen(true)} className="relative flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-white shadow-lg" style={{ backgroundColor: primary }} aria-label={`Open cart with ${cartCount} items`}><ShoppingCart className="h-5 w-5" />{cartCount > 0 && <span className="absolute -right-1 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-white px-1 text-xs font-bold" style={{ color: primary }}>{cartCount}</span>}</button></div><div className={blockProducts ? 'space-y-4' : 'grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-4'}>{data.items.map(renderProduct)}</div></section>,
    contact: hasContact && <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14" aria-labelledby="contact-heading"><p className="text-sm font-semibold" style={{ color: accent }}>Get in touch</p><h2 id="contact-heading" className="mt-1 text-2xl font-bold sm:text-3xl">Contact &amp; Hours</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{data.address?.trim() && <div className="flex gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0" style={{ color: accent }} /><p className="whitespace-pre-line text-sm leading-6 text-slate-600">{data.address}</p></div>}{data.phone?.trim() && <div className="flex gap-3"><Phone className="mt-1 h-5 w-5 shrink-0" style={{ color: accent }} /><a href={`tel:${data.phone}`} className="text-sm leading-6 text-slate-600 hover:underline">{data.phone}</a></div>}{hasHours && <div className="flex gap-3 sm:col-span-2"><Clock3 className="mt-1 h-5 w-5 shrink-0" style={{ color: accent }} /><dl className="grid gap-x-8 gap-y-1 text-sm text-slate-600 sm:grid-cols-2">{Object.entries(openingHours).filter(([, hours]) => hours).map(([day, hours]) => <div key={day} className="flex gap-3"><dt className="w-24 capitalize font-semibold">{day}</dt><dd>{hours}</dd></div>)}</dl></div>}</div>{storefront.whatsapp_number && <a href={whatsappUrl(storefront.whatsapp_number, `Hello ${data.business_name}, I would like to get in touch.`)} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-xl px-4 py-3 text-sm font-semibold text-white" style={{ backgroundColor: accent }}>Contact via WhatsApp</a>}</section>,
  }
  const order = storefront.business_type_hint === 'services' ? ['about', 'services', 'gallery', 'products', 'contact'] : storefront.business_type_hint === 'products' ? ['products', 'about', 'contact', 'services', 'gallery'] : ['about', 'services', 'products', 'gallery', 'contact']

  return <main className={`min-h-screen ${themeClass}`} style={{ '--store-primary': primary, '--store-accent': accent, backgroundColor: themePreset.surface, color: themePreset.ink } as React.CSSProperties}>
    <header className="mx-auto max-w-6xl px-4 pt-4 sm:px-8 sm:pt-8"><div className={`relative overflow-hidden ${themePreset.radius} ${storefront.banner_image ? 'aspect-[16/8] sm:aspect-[16/6]' : 'min-h-24'}`} style={{ backgroundColor: primary }}>{storefront.banner_image ? <img src={storefront.banner_image} alt="" className="h-full w-full object-cover" /> : <div className="h-full w-full" style={{ background: `linear-gradient(120deg, ${primary}, ${accent})` }} />}</div><div className={`relative mx-3 -mt-8 flex flex-col gap-4 border border-slate-200 bg-white p-5 shadow-xl sm:mx-8 sm:-mt-12 sm:flex-row sm:items-center sm:p-7 ${themePreset.radius}`}><div className="flex items-center gap-4">{storefront.logo && <img src={storefront.logo} alt={`${data.business_name} logo`} className="h-16 w-16 rounded-2xl border border-slate-200 bg-white object-cover p-1 shadow-sm sm:h-20 sm:w-20" />}<div><p className="text-xs font-semibold uppercase tracking-[0.25em]" style={{ color: accent }}>{data.items.length > 0 ? 'Online shop' : 'Welcome'}</p><h1 className={`mt-1 font-bold leading-tight ${isBold ? 'text-3xl sm:text-5xl' : 'text-3xl sm:text-4xl'}`}>{data.business_name}</h1>{storefront.description && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base">{storefront.description}</p>}</div></div></div></header>
    {order.map((key) => <div key={key}>{sections[key as keyof typeof sections]}</div>)}
    {socialLinks.length > 0 && <div className="border-t border-slate-200 px-5 py-6" style={{ color: accent }}><div className="flex justify-center gap-3">{socialLinks.map(({ key, label, icon: Icon }) => <a key={key} href={storefront.social_links[key]} target="_blank" rel="noreferrer" aria-label={label} className="flex h-11 w-11 items-center justify-center rounded-full border border-current transition-opacity hover:opacity-70"><Icon className="h-5 w-5" /></a>)}</div></div>}
    <footer className="border-t border-slate-200 px-5 py-8 text-center text-sm text-slate-500"><a href="https://www.vendari.name.ng" className="font-semibold hover:underline">Powered by Vendari</a></footer>
    {inquiryService && <div className="fixed inset-0 z-50"><button type="button" aria-label="Close service inquiry" className="absolute inset-0 bg-slate-950/45" onClick={() => setInquiryService(null)} /><form onSubmit={submitInquiry} className="absolute inset-x-0 bottom-0 mx-auto w-full max-w-md rounded-t-3xl bg-white p-5 shadow-2xl sm:bottom-auto sm:top-1/2 sm:-translate-y-1/2 sm:rounded-3xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Inquire about {inquiryService.name}</h2><p className="mt-1 text-sm text-slate-500">We will open WhatsApp with your message.</p></div><button type="button" onClick={() => setInquiryService(null)} aria-label="Close service inquiry"><X className="h-5 w-5" /></button></div><div className="space-y-3"><input required value={inquiryForm.name} onChange={(event) => setInquiryForm({ ...inquiryForm, name: event.target.value })} placeholder="Your name" className="w-full rounded-xl border border-slate-200 px-4 py-3" /><input required type="tel" value={inquiryForm.phone} onChange={(event) => setInquiryForm({ ...inquiryForm, phone: event.target.value })} placeholder="Phone number" className="w-full rounded-xl border border-slate-200 px-4 py-3" /><textarea required value={inquiryForm.message} onChange={(event) => setInquiryForm({ ...inquiryForm, message: event.target.value })} placeholder="What would you like to ask?" className="min-h-28 w-full rounded-xl border border-slate-200 px-4 py-3" /><button type="submit" disabled={!storefront.whatsapp_number} className="w-full rounded-xl px-4 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50" style={{ backgroundColor: accent }}>Open WhatsApp</button>{!storefront.whatsapp_number && <p className="text-sm text-red-600">This business has not configured WhatsApp yet.</p>}</div></form></div>}
    {cartOpen && <div className="fixed inset-0 z-50"><button type="button" aria-label="Close cart" className="absolute inset-0 bg-slate-950/45" onClick={() => setCartOpen(false)} /><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-white p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><div><h2 className="text-xl font-bold">Your cart</h2><p className="text-sm text-slate-500">{cartCount} item{cartCount === 1 ? '' : 's'}</p></div><button type="button" onClick={() => setCartOpen(false)} aria-label="Close cart"><X className="h-5 w-5" /></button></div><div className="flex-1 space-y-4 overflow-y-auto py-5">{cart.length === 0 ? <p className="py-10 text-center text-slate-500">Your cart is empty.</p> : cart.map((item) => <div key={item.product_name} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{item.product_name}</p><p className="text-sm text-slate-500">{money(item.selling_price)}</p></div><div className="flex items-center gap-2 rounded-full border border-slate-200 px-2 py-1"><button type="button" onClick={() => updateQuantity(item.product_name, -1)} aria-label={`Remove one ${item.product_name}`}><Minus className="h-4 w-4" /></button><span className="w-5 text-center text-sm">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.product_name, 1)} aria-label={`Add one ${item.product_name}`}><Plus className="h-4 w-4" /></button></div></div>)}</div><div className="border-t border-slate-200 pt-4"><div className="flex justify-between text-lg font-bold"><span>Total</span><span style={{ color: primary }}>{money(total)}</span></div><button type="button" disabled={cart.length === 0} onClick={() => { setCartOpen(false); setCheckoutOpen(true) }} className="mt-4 w-full rounded-xl px-4 py-3 font-semibold text-white disabled:opacity-40" style={{ backgroundColor: primary }}>Continue with order</button></div></aside></div>}
    {checkoutOpen && <div className="fixed inset-0 z-50"><button type="button" aria-label="Close checkout" className="absolute inset-0 bg-slate-950/45" onClick={() => setCheckoutOpen(false)} /><form onSubmit={submitCheckout} className="absolute inset-x-0 bottom-0 mx-auto max-h-[92vh] w-full max-w-md overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:bottom-auto sm:top-1/2 sm:-translate-y-1/2 sm:rounded-3xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">Complete your order</h2><button type="button" onClick={() => setCheckoutOpen(false)} aria-label="Close checkout"><X className="h-5 w-5" /></button></div><div className="space-y-3"><input required value={form.customer_name} onChange={(event) => setForm({ ...form, customer_name: event.target.value })} placeholder="Your name" className="w-full rounded-xl border border-slate-200 px-4 py-3" /><input required value={form.customer_phone} onChange={(event) => setForm({ ...form, customer_phone: event.target.value })} placeholder="Phone number" className="w-full rounded-xl border border-slate-200 px-4 py-3" /><textarea value={form.customer_address} onChange={(event) => setForm({ ...form, customer_address: event.target.value })} placeholder="Delivery address (optional for pickup)" className="min-h-24 w-full rounded-xl border border-slate-200 px-4 py-3" /><select value={form.delivery_option} onChange={(event) => setForm({ ...form, delivery_option: event.target.value })} className="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="pickup">Pickup</option><option value="delivery">Delivery</option><option value="both">Delivery or pickup</option></select>{data.has_payments_enabled ? <div className="grid grid-cols-2 gap-2">{(['whatsapp', 'pay_now'] as const).map((method) => <button type="button" key={method} onClick={() => setForm({ ...form, checkout_method: method })} className={`rounded-xl border px-3 py-3 text-sm font-semibold ${form.checkout_method === method ? 'text-white' : 'text-slate-700'}`} style={form.checkout_method === method ? { backgroundColor: primary, borderColor: primary } : undefined}>{method === 'whatsapp' ? 'Order via WhatsApp' : 'Pay Now'}</button>)}</div> : <div className="rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700">Order via WhatsApp</div>}{checkoutError && <p className="text-sm text-red-600">{checkoutError}</p>}<button disabled={submitting} type="submit" className="w-full rounded-xl px-4 py-3 font-semibold text-white disabled:opacity-50" style={{ backgroundColor: accent }}>{submitting ? 'Submitting...' : form.checkout_method === 'whatsapp' ? 'Open WhatsApp' : 'Continue to payment'}</button></div></form></div>}
  </main>
}
