"""
Django settings for vendari_api project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import ast
from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CORS_ALLOWED_ORIGINS=(list, ['http://localhost:3000', 'http://localhost:3002', 'http://127.0.0.1:3000', 'http://127.0.0.1:3002']),
)
environ.Env.read_env(BASE_DIR / '.env')


def parse_referral_tiers(raw_value):
    if raw_value is None:
        return [(1, 5, 20), (6, 20, 25), (21, None, 30)]
    if isinstance(raw_value, str):
        value = raw_value.strip()
        if not value:
            return [(1, 5, 20), (6, 20, 25), (21, None, 30)]
        try:
            parsed = ast.literal_eval(value)
        except (ValueError, SyntaxError) as exc:
            raise ImproperlyConfigured('REFERRAL_TIERS must be a list of 3-tuples like [(1, 5, 20), (6, 20, 25)]') from exc
        if not isinstance(parsed, list):
            raise ImproperlyConfigured('REFERRAL_TIERS must be a list.')
        tiers = []
        for item in parsed:
            if not isinstance(item, (list, tuple)) or len(item) != 3:
                raise ImproperlyConfigured('Each referral tier must be a tuple of (min_count, max_count_or_none, percent).')
            min_count, max_count, percent = item
            tiers.append((int(min_count), None if max_count is None else int(max_count), int(percent)))
        if not tiers:
            raise ImproperlyConfigured('REFERRAL_TIERS cannot be empty.')
        return tiers
    raise ImproperlyConfigured('REFERRAL_TIERS must be provided as a string literal list.')


AUTH_USER_MODEL = 'accounts.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = env.bool('DEBUG', default=False)
if DEBUG and (env('RENDER', default='') or env('RENDER_SERVICE_ID', default='')):
    raise ImproperlyConfigured('DEBUG must be False in the Render environment')
SECRET_KEY = env('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-only-secret-key'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0'] if DEBUG else [])
CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=['http://localhost:3000', 'http://localhost:3002', 'http://127.0.0.1:3000', 'http://127.0.0.1:3002'] if DEBUG else [],
)
PAYSTACK_SECRET_KEY = env('PAYSTACK_SECRET_KEY', default='')
PAYSTACK_MONTHLY_PLAN_CODE = env('PAYSTACK_MONTHLY_PLAN_CODE', default='')
PAYSTACK_YEARLY_PLAN_CODE = env('PAYSTACK_YEARLY_PLAN_CODE', default='')

# These are the canonical, fixed Pro membership prices in kobo.
# The Paystack plan codes remain environment-driven, but the price values should not drift
# between environments or be overridden by stale local env files.
PRO_MONTHLY_KOBO = 499900
PRO_YEARLY_KOBO = 4999000

REFERRAL_SETTINGS = {
    'COMMISSION_WINDOW_MONTHS': env.int('COMMISSION_WINDOW_MONTHS', default=12),
    'HOLD_DAYS': env.int('HOLD_DAYS', default=14),
    'MIN_PAYOUT_KOBO': env.int('MIN_PAYOUT_KOBO', default=500000),
    'DAILY_WITHDRAWAL_CAP_KOBO': env.int('DAILY_WITHDRAWAL_CAP_KOBO', default=5000000),
    'REFERRED_TRIAL_DAYS': env.int('REFERRED_TRIAL_DAYS', default=14),
    'PRO_MONTHLY_KOBO': PRO_MONTHLY_KOBO,
    'PRO_YEARLY_KOBO': PRO_YEARLY_KOBO,
    'TIERS': parse_referral_tiers(env('REFERRAL_TIERS', default='[(1, 5, 20), (6, 20, 25), (21, None, 30)]')),
    'PAYOUT_FEE_KOBO': env.int('PAYOUT_FEE_KOBO', default=0),
    'CONCIERGE_COMMISSION_PERCENT': env.int('CONCIERGE_COMMISSION_PERCENT', default=10),
    'CONCIERGE_HOLD_DAYS': env.int('CONCIERGE_HOLD_DAYS', default=14),
    'FRAUD_SHARED_SIGNUP_THRESHOLD': env.int('FRAUD_SHARED_SIGNUP_THRESHOLD', default=3),
    'FRAUD_INACTIVE_TRIAL_THRESHOLD': env.int('FRAUD_INACTIVE_TRIAL_THRESHOLD', default=3),
    'FRAUD_QUICK_REFUND_DAYS': env.int('FRAUD_QUICK_REFUND_DAYS', default=14),
    'FRAUD_QUICK_CANCEL_DAYS': env.int('FRAUD_QUICK_CANCEL_DAYS', default=7),
    'TRIAL_USAGE_CAPS': {
        'ai_questions': env.int('TRIAL_AI_QUESTIONS_CAP', default=50),
        'voice_entries': env.int('TRIAL_VOICE_ENTRIES_CAP', default=20),
        'whatsapp_messages': env.int('TRIAL_WHATSAPP_MESSAGES_CAP', default=100),
    },
}
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
GEMINI_MODEL = env('GEMINI_MODEL', default='gemini-2.5-flash')
WHATSAPP_ACCESS_TOKEN = env('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_PHONE_NUMBER_ID = env('WHATSAPP_PHONE_NUMBER_ID', default='')
WHATSAPP_DISPLAY_NUMBER = env('WHATSAPP_DISPLAY_NUMBER', default='')
WHATSAPP_BUSINESS_ACCOUNT_ID = env('WHATSAPP_BUSINESS_ACCOUNT_ID', default='')
WHATSAPP_CATALOG_ID = env('WHATSAPP_CATALOG_ID', default='')
WHATSAPP_APP_SECRET = env('WHATSAPP_APP_SECRET', default='')
WHATSAPP_WEBHOOK_VERIFY_TOKEN = env('WHATSAPP_WEBHOOK_VERIFY_TOKEN', default='')
VENDARI_LOGO_URL = env('VENDARI_LOGO_URL', default='')
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
GOOGLE_REDIRECT_URI = env('GOOGLE_REDIRECT_URI', default='')
GOOGLE_FRONTEND_REDIRECT_URI = env('GOOGLE_FRONTEND_REDIRECT_URI', default='')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'accounts',
    'businesses',
    'inventory',
    'sales',
    'expenses',
    'customers',
    'notifications',
    'invoices',
    'billing',
    'referrals',
    'ai_insights',
    'whatsapp',
    'broadcasts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vendari_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendari_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        **env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=60),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'accounts.permissions.IsBusinessMember',
    ),
}

RESEND_API_KEY = env('RESEND_API_KEY', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='onboarding@resend.dev')
ADMIN_EMAIL_FROM = env('ADMIN_EMAIL_FROM', default='Vendari Support Team <support@vendari.name.ng>')
EMAIL_BACKEND = env('EMAIL_BACKEND', default='vendari_api.resend_backend.ResendBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=0)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=10)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DASHBOARD_URL = env('DASHBOARD_URL', default=(CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else 'http://localhost:3000'))
FRONTEND_URL = env('FRONTEND_URL', default=DASHBOARD_URL)
SENTRY_DSN = env('SENTRY_DSN', default='')

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env('JWT_SECRET_KEY', default=SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

CRON_SECRET = env('CRON_SECRET', default='')

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_BEAT_SCHEDULE = {
    'compute-business-insights-nightly': {
        'task': 'ai_insights.tasks.compute_all_business_insights',
        'schedule': 60 * 60 * 24,
    },
    'approve-pending-referral-commissions': {
        'task': 'referrals.tasks.approve_pending_commissions',
        'schedule': 60 * 60,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
CLOUDINARY_URL = env('CLOUDINARY_URL', default='')
if CLOUDINARY_URL:
    CLOUDINARY_STORAGE = {'CLOUDINARY_URL': CLOUDINARY_URL}
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    CLOUDINARY_STORAGE = {}
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration to ensure welcome email diagnostics are captured
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'billing': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        send_default_pii=False,
        traces_sample_rate=0,
    )
