# Generated by Django 5.2.17 on 2026-09-18 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_storefrontsettings_product_display_mode'),
        ('customers', '0001_initial'),
        ('invoices', '0002_invoicepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('payment', 'Payment reminder'), ('reengagement', 'Re-engagement reminder')], default='payment', max_length=30)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reminders', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='customers.customer')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reminders', to='invoices.invoice')),
            ],
            options={
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['business', 'customer', 'reminder_type', 'sent_at'], name='customers_c_busines_7ca81f_idx')],
            },
        ),
    ]
