# Generated by Django 5.2.17 on 2026-09-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_storefrontorder_payout_status'),
        ('sales', '0003_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='storefront_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='businesses.storefrontorder'),
        ),
    ]
